POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRpbW9ua2F5dHRhamEiLCJpZCI6MSwiaWF0IjoxNzUwNDk4MTU2fQ.j84LaV-y2BxGsXJzfiC9uwWCEeDy5bXAVTvp_jq0ocI

{
    "author": "jari",
    "url": "www.blogi.com",
    "likes": "9",
    "title": "jarin blog"
}